<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DT-AKASHM" ignored="1" name="Default test" tests="3" failures="0" timestamp="08 Aug 2017 11:23:38 GMT" time="8.888" errors="0">
  <testcase name="@AfterMethod getResult" time="0.007" classname="com.selenium.generic.util.BaseClass">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.selenium.generic.util.BaseClass.getResult(BaseClass.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:723)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- @AfterMethod getResult -->
  <testcase name="@BeforeMethod getStatus" time="0.0" classname="com.selenium.generic.util.BaseClass">
    <skipped/>
  </testcase> <!-- @BeforeMethod getStatus -->
  <testcase name="@BeforeMethod getStatus" time="0.0" classname="com.selenium.generic.util.BaseClass">
    <skipped/>
  </testcase> <!-- @BeforeMethod getStatus -->
  <testcase name="TC_002" time="0.296" classname="com.selenium.test.functional.DatePickerUC"/>
  <testcase name="TC_003" time="0.0" classname="com.selenium.test.functional.DatePickerUC">
    <skipped/>
  </testcase> <!-- TC_003 -->
  <testcase name="TC_004" time="0.0" classname="com.selenium.test.functional.DatePickerUC">
    <skipped/>
  </testcase> <!-- TC_004 -->
  <testcase name="TC_001" time="0.0" classname="com.selenium.test.functional.DatePickerUC">
    <ignored/>
  </testcase> <!-- TC_001 -->
</testsuite> <!-- Default test -->
